### ISSUE TITLE
Use of numeric_limits instead of limit constants

### ISSUE THREAD

**Issue by AquilesCanta** [hhsaez/crimild#3]
Allows compilation with g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

diff --git a/core/src/Foundation/FixedAllocator.hpp b/core/src/Foundation/FixedAllocator.hpp
index c274a8c..e8007f9 100644
--- a/core/src/Foundation/FixedAllocator.hpp
+++ b/core/src/Foundation/FixedAllocator.hpp
@@ -43,7 +43,7 @@ namespace crimild {
 
 		private:
 			static constexpr unsigned char MIN_OBJECTS_PER_CHUNK = 8;
-			static constexpr unsigned char MAX_OBJECTS_PER_CHUNK = UCHAR_MAX;
+			static constexpr unsigned char MAX_OBJECTS_PER_CHUNK = std::numeric_limits<unsigned char>::max();
 
 		private:
 			using ChunkArray = std::vector< Chunk >;

**Comment by hhsaez** [comment]
I made the change in the devel branch and will be published in next release. Good catch!
